/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmoptconfig_free: (a: number, b: number) => void;
export const wasmoptconfig_new: () => number;
export const wasmoptconfig_quality: (a: number) => number;
export const wasmoptconfig_set_quality: (a: number, b: number) => void;
export const wasmoptconfig_preserve_metadata: (a: number) => number;
export const wasmoptconfig_set_preserve_metadata: (a: number, b: number) => void;
export const wasmoptconfig_lossless: (a: number) => number;
export const wasmoptconfig_set_lossless: (a: number, b: number) => void;
export const wasmoptconfig_reduce_colors: (a: number) => number;
export const wasmoptconfig_set_reduce_colors: (a: number, b: number) => void;
export const wasmoptconfig_target_reduction: (a: number) => number;
export const wasmoptconfig_set_target_reduction: (a: number, b: number) => void;
export const wasmoptconfig_preserve_alpha: (a: number) => number;
export const wasmoptconfig_set_preserve_alpha: (a: number, b: number) => void;
export const imageoptimizer_new: () => number;
export const imageoptimizer_process_image_file: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => any;
export const imageoptimizer_get_image_info: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const meshoptimizer_new: () => number;
export const meshoptimizer_process_mesh_file: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const __wbg_filehandler_free: (a: number, b: number) => void;
export const filehandler_read_file_as_bytes: (a: any) => any;
export const filehandler_create_download_url: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const __wbg_canvasrenderer_free: (a: number, b: number) => void;
export const canvasrenderer_new: (a: any) => [number, number, number];
export const canvasrenderer_load_and_render_image: (a: number, b: number, c: number) => any;
export const canvasrenderer_clear: (a: number) => void;
export const __wbg_progresscallback_free: (a: number, b: number) => void;
export const progresscallback_new: (a: any) => number;
export const progresscallback_update: (a: number, b: number, c: number, d: number) => [number, number];
export const supported_image_formats: () => [number, number];
export const get_format_support_info: (a: number, b: number) => any;
export const supported_mesh_formats: () => [number, number];
export const main: () => void;
export const __wbg_meshoptimizer_free: (a: number, b: number) => void;
export const __wbg_imageoptimizer_free: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const closure4_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__ha4d2336f14cfaaf8: (a: number, b: number) => void;
export const closure100_externref_shim: (a: number, b: number, c: any) => void;
export const closure1015_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
